# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - epub

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .
    - method: setuptools
      path: package
