name: robotframework-jupyterlibrary

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - geckodriver
  - firefox =78
  - isort <5
  - jupyterlab <1
  - nbsphinx
  - nodejs >=10
  - nteract_on_jupyter
  - pillow
  - pip
  - python >=3.6,<3.7
  - robotframework >=3.2
  - robotframework-lint
  - robotframework-seleniumlibrary >=4.5
  - six
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autobuild
