name: robotframework-jupyterlibrary

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - geckodriver
  - isort
  - jupyterlab >=0.35
  - nodejs
  - pillow
  - python-chromedriver-binary
  - robotframework >=3.1
  - robotframework-lint
  - robotframework-seleniumlibrary >=3.2
  - six
  - pip:
    - nteract_on_jupyter
