name: robotframework-jupyterlibrary

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - geckodriver
  - isort
  - jupyterlab
  - nodejs
  - pillow
  - python-chromedriver-binary
  - robotframework
  - robotframework-lint
  - robotframework-seleniumlibrary
  - six
  - pip:
    - nteract_on_jupyter
