channels:
  - conda-forge
  - nodefaults
dependencies:
  # enough stuff to run doit
  - doit
  - pip
  - pyyaml
  # really nothing for it
  - nodejs >=10,!=11.*,!=13.*,!=15.*,!=17.*
  # hard deps
  - robotframework >=3.2
  - robotframework-seleniumlibrary >=4.5
