channels:
  - conda-forge
  - nodefaults
  - msys2
dependencies:
  # enough stuff to run doit
  - doit
  - pip
  - pyyaml
  # hard deps
  - robotframework >=3.2
  - robotframework-seleniumlibrary >=4.5
