# TODO: fully support in the matrix

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ipywidgets >=7.6,<8.0.0a0
  - jupyter_server >=1.2,<2.0.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - jupyterlab_server >=2.0.0,<3.0.0a0
