parameters:
  name: Linux
  vmImage: ubuntu-16.04

jobs:
  - job: Combine
    condition: always()
    pool:
      vmImage: ${{ parameters.vmImage }}
    dependsOn:
      - Linux
      - MacOSX
      - Windows
    steps:
      - template: steps.conda.yml
        parameters:
          name: Linux
      - task: DownloadPipelineArtifact@0
        condition: always()
        inputs:
          artifactName: JupyterLibrary Linux Robot Logs
          targetPath: _artifacts/test_output
      - task: DownloadPipelineArtifact@0
        condition: always()
        inputs:
          artifactName: JupyterLibrary MacOSX Robot Logs
          targetPath: _artifacts/test_output
      - task: DownloadPipelineArtifact@0
        condition: always()
        inputs:
          artifactName: JupyterLibrary Windows Robot Logs
          targetPath: _artifacts/test_output
      - script: python -m scripts.combine
        condition: always()
        displayName: Rebot
      - task: PublishPipelineArtifact@0
        condition: always()
        displayName: Publish Robot Logs
        inputs:
          targetPath: _artifacts/test_output
          artifactName: JupyterLibrary Combined Robot Logs
