# TODO: automate generating this
name: rtd

channels:
  - conda-forge
  - nodefaults
  - msys2

dependencies:
  # enough stuff to run doit
  - doit
  - pip
  - pyyaml
  # really nothing for it
  - nodejs >=10,!=11.*,!=13.*,!=15.*,!=17.*
  # hard deps
  - robotframework >=3.2
  - robotframework-seleniumlibrary >=4.5
  # docs only
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autobuild
  - port-for =0.3.1
  - ipykernel
